### ISSUE TITLE
Development: Visualization of the data

### ISSUE THREAD

**Issue by PiotrBenedysiuk** [PiotrBenedysiuk/Data_mine_dennis#4]
Someone needs to work on making plots. Share ideas please: histograms, time of day plots, time until end vs amount of average links...

**Comment by PestoSandwich** [comment]
Amount of replies within half an hour. I want data about how little people respond :)

**Comment by PiotrBenedysiuk** [comment]
Panda's framework has been added in a358e39. Plotting never been easier!
